dependencies:
  # Items required for basic level functionality
  - gh-scoped-creds==4.1
  - git==2.47.1
  - jupyter-archive==3.4.0
  - jupyter-offlinenotebook==0.3.1
  - jupyter-resource-usage==1.1.0  
  - jupyter-server-proxy==4.4.0
  - jupyter_server==2.15.0 
  - jupyterhub==5.2.1
  - jupyterlab==4.3.4
  - jupyterlab-git==0.50.2
  - jupyterlab_rise==0.43.1
  - jupytext==1.16.6
  - nbgitpuller==1.2.1
  - notebook==7.3.2
  - otter-grader==6.1.0
  - pip==24.3.1  
  - python==3.11.*


  # data8
  - attrs==24.3.0
  - datascience==0.17.6
  - folium==0.15.1
  - ipykernel==6.29.5
  - ipympl==0.9.4
  - ipywidgets==8.1.5
  - matplotlib==3.8.*
  - nbclassic==1.0.0
  - pandas==2.2.2
  - scipy==1.11.3
  - seaborn==0.13.2
  - statsmodels==0.14.1
  - syncthing==1.18.6
  - traitlets=5.14.3


  # Items not in conda forge
  - pip:
    - jupyter-tree-download==1.0.1
  # Export notebooks as PDFs with Chrome
    - nb2pdf==0.6.2
    - nbpdfexport==0.2.1
  # Enable webpdf export DH-325
    - nbconvert[webpdf]==7.16.5
    - git-credential-helpers==0.2
  # [DH-418] okpy 1.18.1 is not compatibile with otter-grader 6.0.4 because they require conflicting versions of requests
  #  - okpy==1.18.1
    - git+https://github.com/shaneknapp/python-popularity-contest.git@add-error-handling

